site_name: My Blog
theme:
  name: material
  favicon: ./Fav.png
  logo: ./Fav.png



  features:
    # - navigation.tabs
    - toc.integrate
    - navigation.instant
    - navigation.instant.progress
    #- navigation.sections
    #- navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: white
      accent: red 
    - scheme: slate 
      toggle:
        icon: material/lightbulb
        name: Switch to light mode    
      primary: white
      accent: amber

extra:
  version:
    provider: mike

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list

extra_css:
  - ./extra.css
extra_javascript:
  - ./extra.js

plugins:
  - search

nav:
  - Home: ./index.md

